[project]
name = "bikerentalestimation-mlops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "MarT1AZ", email = "mewpudit@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "pytest>=9.1.1",
    "s3fs>=2026.7.0",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[project.scripts]
bikerentalestimation-mlops = "bikerentalestimation_mlops:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
